### ISSUE TITLE
Removing integrator from simulation after attaching

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/hoomd-blue#1052] opened 2021-07-07 21:26 UTC
## Description

Removing an integration method from the integrator after attaching leads to an error. The problem has to do with the new manifold constraints.

I would also like to add that the `test_attributes_attached` test in `md/test_manifolds.py` does not actually test that the manifold parameters are correct after attaching since it is not given to the integration method.

## Script

```python
import numpy as np

import hoomd
from hoomd import md

def make_snapshot():
    snap = hoomd.Snapshot()
    snap.particles.N = 2
    snap.particles.position[:] = np.array([[-1, 0, 0], [1, 0, 0]])
    snap.particles.types = ['A']
    snap.particles.typeid[:] = [0, 0]
    return snap

d = hoomd.device.CPU()
sim = hoomd.Simulation(d)
snap = make_snapshot()
sim.create_state_from_snapshot(snap)

nve = md.methods.NVE(hoomd.filter.All())
md_int = md.Integrator(dt=0.05, methods=[nve])
sim.operations.integrator = md_int
sim.run(5)
md_int.methods.remove(nve)  # error comes here
```

## Output

Traceback (most recent call last):
  File "/nfs/turbo/bi-vislab/tomwalt/scripts/hoomd/manifold_error.py", line 23, in <module>
    md_int.methods.remove(nve)  # error comes here
  File "/usr/lib/python3.9/_collections_abc.py", line 1107, in remove
    del self[self.index(value)]
  File "/scratch/tomwalt/hoomd-builds/dev-build/hoomd/data/syncedlist.py", line 161, in __delitem__
    self._list[index]._detach()
  File "/scratch/tomwalt/hoomd-builds/dev-build/hoomd/operation.py", line 232, in _detach
    self._update_param_dict()
  File "/scratch/tomwalt/hoomd-builds/dev-build/hoomd/operation.py", line 278, in _update_param_dict
    self._param_dict[key] = getattr(self, key)
  File "/scratch/tomwalt/hoomd-builds/dev-build/hoomd/operation.py", line 45, in __getattr__
    return self._getattr_param(attr)
  File "/scratch/tomwalt/hoomd-builds/dev-build/hoomd/md/methods.py", line 82, in _getattr_param
    parameter = getattr(self._cpp_obj, attr)
AttributeError: 'hoomd.md._md.TwoStepNVE' object has no attribute 'tolerance'

## Expected output

None

## Configuration

Running on the vislab

Platform:
- Linux
- CPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.9.5
- **HOOMD-blue** version: most up to date master, which includes the beta-7

## Developer
Phillip could do it, since he wrote the manifold stuff. I could take a look at it if he's not available

**Comment by joaander** [comment] 2021-07-07 22:06
duplicate of #998

**Closed by joaander** 2021-07-07 22:06 UTC
Labels: API 3.0, bug, md, testing

**Comment by SchoeniPhlippsn** [comment] 2021-07-09 17:27
I will have a look at it!
