### ISSUE TITLE
Doc rendering issues

### ISSUE THREAD

**Issue by bdice** [glotzerlab/hoomd-blue#1001] opened 2021-05-21 01:54 UTC
Some docstrings aren't rendering correctly. I wasn't immediately sure how to fix the rendering or I would have made a PR.

https://github.com/glotzerlab/hoomd-blue/blob/c596d2c570d3c1d2d161b7f0fcccb2d4ad6e86eb/hoomd/md/force.py#L63-L64
https://hoomd-blue.readthedocs.io/en/latest/module-md-force.html#hoomd.md.force.Force.energies
![image](https://user-images.githubusercontent.com/3943761/119070037-e3113000-b9ac-11eb-855c-4b47880ccbdf.png)

**Comment by vyasr** [comment] 2021-05-21 06:28
I would guess that the problem is that Sphinx doesn't correctly handle formatting when the first line of the docstring is split over two lines. This is why so many docstrings in our other packages end up putting in a `noqa: E501` on docstrings, to avoid line breaks that result in poor formatting like this.

**Comment by joaander** [comment] 2021-05-24 18:00
This is now fixed on master. 

For future reference, there are two likely causes for formatting that looks like this.

1. A list is not indented properly on line continuation. Example (incorrect):
```
* This is a list item
    broken across lines
```

restructured text formats this as a definition list. The intention is for a single bulleted list item. To get that, line up the start of the continued line with the start of the first line (b with T in this example). Note that this means indenting by 2 chars for `*` and `-`, but 3 for `1.` in lists. Many editors auto-indent and unindent features do not work so well with this and try to force things on multiples of 4 characters.

Correct:
```
* This is a list item
  broken across lines
```

2. Google formatting in napoleon parses only the first line in a property docstring as its type and short description. When that short description is too long (example):
```
@property
def energy()
    """(float) This is a long line
    that needs to be broken."""
```

It either needs to be reworded to be shorter, or use `\` to make the line continued:
```
@property
def energy()
    """(float) This is a long line \
    that needs to be broken."""
```

There is one caveat here. When a single-line type and short description is in a `r"""` docstring, the `\` will be included in the string and will not continue the line :( The only option I found here, is to drop Google formatting in these cases and use `.. py:attribute::` directly. Example:

```
    .. py:attribute:: params

        The LJ potential parameters. The dictionary has the following keys:

        * ``epsilon`` (`float`, **required**) -
          energy parameter :math:`\varepsilon` (units: [energy])
        * ``sigma`` (`float`, **required**) -
          particle size :math:`\sigma` (units: [length])
        * ``alpha`` (`float`, **required**) -
          controls well-width :math:`\alpha` (unitless)

        Type: `TypeParameter` [`tuple` [``particle_type``, ``particle_type``],
        `dict`]
```
This allows the type to be placed on a separate line from the short description. This is often needed with `TypeParameter` types which get quite long.

**Closed by joaander** 2021-05-24 18:00 UTC
Labels: documentation

**Comment by vyasr** [comment] 2021-05-26 03:02
@joaander just FYI, most of our other code bases instead choose to simply request that `flake8` ignore the line-length check on such docstrings to avoid adding explicit line breaks or have to do the more hackish work of mixing raw Sphinx with Google style. Up to you which you prefer to see in the HOOMD code base though.

**Comment by joaander** [comment] 2021-05-26 14:50
flake8's `noqa` works when it is on the same line as the offending error. Inside of a long multiline string the `# noqa` would be part of the string contents when placed on such a line.

**Comment by vyasr** [comment] 2021-05-26 18:32
Correct, you would have to avoid line-length checks for the entire multi-line comment ([here's an example from freud](https://github.com/glotzerlab/freud/blob/master/freud/pmft.pyx#L193)), which does work but is certainly very heavy-handed. I completely understand if you don't want to do that in HOOMD, just pointing out that this is an option.

**Comment by joaander** [comment] 2021-05-26 18:34
Another workaround would be to ignore `D301 Use r""" if any backslashes in a docstring` and use `\\` where backslashes are needed. Though this does get annoying when there are a lot of backslashes in LaTeX formatting.

**Comment by bdice** [comment] 2021-05-26 18:46
I prefer the alternatives mentioned above over mixing Google / Sphinx docstring styles. Backslashes and/or `noqa` are probably easier to understand and maintain than switching between docstring formats.

**Comment by vyasr** [comment] 2021-05-26 18:48
Agreed, it would work but be annoying. I rarely need raw strings unless I'm typesetting latex (math) in there at which point raw strings are no longer optional anyway. In any case, my main preference is to choose an option that minimizes switching between different styles, which introduces an unnecessary fluid representation for developers who are not as familiar with the available docstring styles. That said, I don't have a strong preference and will defer to whichever you choose.
