### ISSUE TITLE
Running PPPM on water molecules as rigid bodies

### ISSUE THREAD

**Issue by adela-habib** [glotzerlab/hoomd-blue#1645] opened 2023-10-31 16:41 UTC
### Description

Hello, 

I am running PPPM on water molecules using the PPPM pair potential to account for long range electrostatics. When I am setting the constituent hydrogen elements and want to set their charges. But I get the following error:

### Script

```python
import itertools
import math
import gsd.hoomd
import hoomd
import os
from pyinstrument import Profiler
unitConv = 1/10.  # to nm
import numpy as np
from ase.calculators.tip3p import TIP3P, angleHOH, rOH

# Set up water box at 20 deg C density
x = angleHOH * np.pi / 180 / 2
pos = [[0, 0, 0],
       [0, rOH * np.cos(x), rOH * np.sin(x)],
       [0, rOH * np.cos(x), -rOH * np.sin(x)]]

#Make rigid body
simulation = hoomd.Simulation(device=hoomd.device.GPU(), seed=4)
simulation.create_state_from_gsd(filename='O_centers.gsd')
simulation.state.replicate(15,15,15)
rigid = hoomd.md.constrain.Rigid()
HH_positions = np.array([[0, rOH * np.cos(x), rOH * np.sin(x)], [0, rOH * np.cos(x), -rOH * np.sin(x)]])*unitConv
rigid.body['O'] = {
    "constituent_types": ['H', 'H'],
    "positions": HH_positions,
    "orientations": [(1.0, 0.0, 0.0, 0.0), (1.0, 0.0, 0.0, 0.0)],
}
rigid.create_bodies(simulation.state, charges={"H":[+0.417*0.0848385920,+0.417*0.0848385920]}) ##Error########

#Simulate MD with long range interaction
os.system('pppmwaterRigidlog.h5')
os.system('pppmwaterRigidTraj.gsd')

deltaTime = 0.0002 #fs
integrator = hoomd.md.Integrator(dt=deltaTime, integrate_rotational_dof=True)
simulation.operations.integrator = integrator
integrator.rigid = rigid

#MD ensemble
kT = 2.48 #300K
rigid_centers_and_free = hoomd.filter.Rigid(("center", "free"))
nvt = hoomd.md.methods.ConstantVolume(
    filter=rigid_centers_and_free,
    thermostat=hoomd.md.methods.thermostats.Bussi(kT=kT))
integrator.methods.append(nvt)

cell = hoomd.md.nlist.Cell(buffer=0, exclusions=['body'])
short, long=hoomd.md.long_range.pppm.make_pppm_coulomb_forces(nlist=cell, 
                                                              resolution=[64,64,64], 
                                                              order=1, 
                                                              r_cut=10*unitConv, 
                                                              alpha=0) 
integrator.forces.append(short)
integrator.forces.append(long)
#Initial velocities
simulation.state.thermalize_particle_momenta(filter=rigid_centers_and_free,
                                             kT=kT)
#Analyze thermo properties
thermodynamic_properties = hoomd.md.compute.ThermodynamicQuantities(filter=rigid_centers_and_free)
simulation.operations.computes.append(thermodynamic_properties)
#Log thermo properties and trajectory
logger = hoomd.logging.Logger(categories=['scalar', 'sequence'])
logger.add(thermodynamic_properties)
logger.add(simulation, quantities=['timestep', 'walltime'])

hdf5_writer = hoomd.write.HDF5Log(trigger=hoomd.trigger.Periodic(10),
                                  filename='pppmwaterRigidlog.h5',
                                  mode='x',
                                  logger=logger)
simulation.operations.writers.append(hdf5_writer)
gsd_writer = hoomd.write.GSD(filename='pppmwaterRigidTraj.gsd',
                             trigger=hoomd.trigger.Periodic(10),
                             mode='xb')
simulation.operations.writers.append(gsd_writer)
simulation.run(1000)
```

### Input files

[O_centers.gsd.zip](https://github.com/glotzerlab/hoomd-blue/files/13219076/O_centers.gsd.zip)

### Output

```shell
rigid.create_bodies(simulation.state, charges={"H":[+0.417*0.0848385920,+0.417*0.0848385920]}) ##Error########
  File "/vast/home/ahabib/Software/env-sedac/hoomd-trial/lib/python3.10/site-packages/hoomd/md/constrain.py", line 316, in create_bodies
    self._cpp_obj.createRigidBodies({} if charges is None else charges)
RuntimeError: Charge provided for non-central particle type.
```

### Expected output

That the constituent hydrogens will have their charges set without any issues.

### Platform

GPU

### Installation method

Conda package

### HOOMD-blue version

4.2.1

### Python version

3.10.12

**Comment by joaander** [comment] 2023-10-31 17:06
The documentation states that the keys should be the central particle types. Try `charges={"O":[+0.417*0.0848385920,+0.417*0.0848385920]}`.

**Comment by adela-habib** [comment] 2023-10-31 23:04
Thank you for your reply. Does it mean that those charges then over-write the charge specified for central particle which is O?

**Comment by joaander** [comment] 2023-11-01 10:51
No. `create_bodies` is an optional step that creates the *constituent* particles. It leaves all the central particles 'O' in the system state as you placed them. You can verify by inspecting the system state after calling `create_bodies`.

**Comment by joaander** [comment] 2023-11-02 17:03
Did this solve your issue?

**Comment by adela-habib** [comment] 2023-11-03 00:10
I am not able to access charges by looking at simulation.state. Where can I see the charges of the central particle and the constituents?

**Comment by joaander** [comment] 2023-11-03 00:30
There are many ways to access the system state, as covered in the tutorials:
* https://hoomd-blue.readthedocs.io/en/v4.3.0/package-hoomd.html#hoomd.State.get_snapshot
* https://hoomd-blue.readthedocs.io/en/v4.3.0/package-hoomd.html#hoomd.State.cpu_local_snapshot
* https://hoomd-blue.readthedocs.io/en/v4.3.0/module-hoomd-write.html#hoomd.write.GSD

**Comment by adela-habib** [comment] 2023-11-03 19:52
Thank you for the links. I could access the charges and they sum to zeros if I look at a snapshot. I see that the charges now are a rigid body attribute and not a per atom quantity in the rigid body. 
How can one go about accounting for atomic level charge interactions in MD here?

**Comment by joaander** [comment] 2023-11-03 20:29
Thank you for confirming this is not a bug. I will close this issue. The hoomd-users mailing list is the best place for general user support.

Charges are *not* a rigid body attribute. Every particle in the simulation box has a charge associated with it as defined in the documentation for `State`. As I said earlier, `create_bodies` is a *convenience* method to create these particles. You can also place them in the `State` manually. Every particle in the simulation box has a charge associated with it as defined in the documentation for `State`. As I said earlier, `create_bodies` is a *convenience* method to create these particles. You can also place them in the `State` manually. `constrain.Rigid` does not modify the charges of constituent particles as stated in the documentation.

**Closed as completed by joaander** 2023-11-03 20:29 UTC
Labels: bug
