### ISSUE TITLE
Reorder actions in run()

### ISSUE THREAD

**Issue by joaander** [glotzerlab/hoomd-blue#574] opened 2020-01-21 14:51 UTC
## Description

Change the order of operations in `run()` so that analyzers run last.

## Proposed solution

`run()` should run steps in this order:
1. Updaters (at step t)
2. Integrator (move system to step t+1)
3. Analyzers (at step t+1)

## Additional context

This solves user confusion where (e.g.) a trajectory dump with period=100 and run(1000) fails to write output for step 1000. This change also enables simplified single file trajectory/restart workflows with no need for `write_restart` at the end of the script.

As a downside, output files will no longer include step 0.

**Comment by jglaser** [comment] 2020-01-21 15:33
I am not sure if this change is beneficial. With the current implementation, it's always possible to log the last frame by running one more step and restarting from the last frame. With the proposed scheme, it's never possible to analyze the first frame or initial configuration, which the user should be possible to do. Maybe it helps better documenting the order of time step operations and their intended purpose, thus resolving the confusion. Alternatively, you could provide an option to run Analyzers either before **OR** after the update.

**Comment by joaander** [comment] 2020-01-21 18:03
I would welcome discussion from a number of users on this topic as it is a fundamental change to how HOOMD operates. There are a lot of good reasons on both sides. I'd prefer to pick one and stick with it rather than adding the complication of a mode switch.

I don't see how running +1 additional step solves this in a general way. All updaters/analyzers that trigger on that step then they will trigger twice: once at the end of the first run and again on the first timestep of the next run. I don't think that users should expect to see the same frame output written twice to the gsd file, log file, etc...

If I recall correctly, @b-butler suggested considering a flag that users can opt-in to writing output on the first step of a run().

**Comment by mphoward** [comment] 2020-01-21 18:25
I find the frustration of not getting that last step worth changing the behavior so that analyzers fire on t+1. But, I do think they should output on t=0 (it would be annoying to have to constantly add the initial configuration back into a gsd, for example, for rendering a movie). So, I would propose that all analyzers be forced to run either on t=0 (alternatively, if a flag is set) if firing at t+1 OR at the end of the run command if firing at t. I tend to prefer the first, since this probably makes restartable jobs easier (avoiding duplication of the analyzer).

**Comment by jglaser** [comment] 2020-01-23 17:32
The intended behavior can be achieved with the current implementation, as follows:

```python
import os
restart = os.path.exists('trajectory.gsd')

if restart:
    run(1) # run one time step before creating logger, so that no duplicate output is written

log = hoomd.analyze.log(quantities=['potential_energy',...], filename='md.log', period=100)
gsd = hoomd.dump.gsd(filename='trajectory.gsd', group=hoomd.group.all(), period=1000)

run(1e9-1)

# run just one more time step to write last configuration
run(1)
```

As is obvious, the last two steps can be combined in a single `run(1e9)`. It may be easiest to just document this suggested solution instead of changing the default?

**Comment by joaander** [comment] 2020-01-23 19:16
Jens's comment is a replay to an offline message where I proposed a simple restartable job with the proposed run(1) at the end to ensure that the final output is written. The problem is that it duplicates output on the first frame of every restart.
```
import hoomd, hoomd.hpmc
hoomd.context.initialize()
hoomd.init.read_gsd(filename='traj.gsd', frame=-1)

mc = hoomd.hpmc.integrate.sphere(d=0.1, seed=1)
mc.shape_param.set('A', diameter=1.0)

d = hoomd.dump.gsd("traj.gsd", period=50, group=hoomd.group.all())

hoomd.analyze.log(filename="log.dat", quantities=['hpmc_translate_acceptance'], period=10)

hoomd.run(100)
hoomd.run(1)
```

**Comment by joaander** [comment] 2020-01-23 19:20
To put this conversation into a simple context, the current behavior is:
```
state[0] = read_input()
for i in range(0,steps):
    write_output(state[i])
    state[i+1] = f(state[i])
```

The proposed change is:
```
state[0] = read_input()
if (step == 0)
    write_output(state[0])

for i in range(1,steps+1):
     state[i] = f(state[i-1])
     write_output(state[i])
```

**Comment by tommy-waltmann** [comment] 2020-01-23 19:41
I don't think any change is necessary. Why is it so important to get the last log data point or dump frame in your trajectory in the first place? Simulations are generally run until the system is well equilibrated, and at that point, there should be many frames in your trajectory at the end of the dump file that could represent the system in equilibrium.

If your simulation hasn't reached equilibrium or has just reached equilibrium, and you really need that last frame, just run the simulation out slightly longer.

**Comment by j-proc** [comment] 2020-01-23 20:41
@tommy-waltmann In general you're correct. But the user should be in control of this. It's actually pretty important for reproducibility and it's also important for some advanced methods like rare event sampling where things aren't in equilibrium yet and thus the order is critical.

I agree with the proposed change. It is a difference, but considering that this is a change for a major release, I don't think that's a reason to not do it. Considering that current practice already includes a workaround, it makes sense to make the more common sense behavior the standard. From a programming standpoint, the previous behavior makes sense with our language choices. But for most scientists, period evokes something like a sine wave where you'd expect the full output to be covered by multiples of the period.

As for the details of how the flag is implemented, I'm just wondering if it makes sense to make it a flag per output function or a sort of global with run.

**Comment by mphoward** [comment] 2020-01-23 20:41
> Why is it so important to get the last log data point or dump frame in your trajectory in the first place?

Imagine you are running a simulation where it is expensive to dump full frames (but you need them), and you dump them infrequently because (1) they take up alot of space or (2) the dynamics are sluggish so they're too correlated. For example, I want to run 1e7 steps and dump a frame every 1e6 steps. With the current behavior, I lose the last 10% of my simulation time if I forget to run 1e7+1 steps because the final configuration does not get written to file. Also, not all simulations are at equilibrium, so just running longer is not always an option.

I fully support Josh's proposed change as it's simple and clean. Although Jens' workaround is feasible, it seems pretty unwieldy to me, and I know I would make mistakes implementing it. (I'd be more likely to just run the simulation and then excise any duplicate output during the analysis.) One question: should it be only `step == 0`, or could there be an additional flag to force the initial write? I'm thinking of cases where the initial configuration is at step > 0 (say, coming from an equilibration run), but you still want to start writing output to files when the production simulation starts. It's OK by me if this behavior is not allowed.

**Comment by b-butler** [comment] 2020-01-24 02:15
I personally prefer @joaander's solution. However, with the `if step == 0` I think that that functionality may be better served using a flag in the run function signature. I think that since we always start with some state zero, writing that state instead of the system's last state doesn't make intuitive sense (in that I wouldn't expect someone unfamiliar with the code to expect that behavior).

**Comment by bdice** [comment] 2020-01-24 19:22
I like the proposals/reasons posed above for including both the starting and final frames, OR keeping the current behavior (no "final frame"). I am opposed to "no starting frame," since initial configurations are often even more important/useful than final configurations when trying to understand someone else's data. In my own simulations, I almost always use something like `hoomd.run(target+1)` to get the final frames.

**Comment by joaander** [comment] 2020-09-16 16:34
> One question: should it be only `step == 0`, or could there be an additional flag to force the initial write? I'm thinking of cases where the initial configuration is at step > 0 (say, coming from an equilibration run), but you still want to start writing output to files when the production simulation starts. It's OK by me if this behavior is not allowed.

Yes, it should be an opt-in flag that defaults to False so that users can get the initial and/or duplicate output if they wish it:
```
sim.run(steps, write_initial_state=True)
```

**Comment by bdice** [comment] 2020-09-16 17:11
If this affects all analyzers (not just file-dumpers) then maybe a more generic name than `write_initial_state` would be appropriate (to me, that sounds like it will only trigger GSD file writes, but ideally all analyzer-triggers would fire?). I tried to come up with a better name and struggled.

**Comment by joaander** [comment] 2020-09-16 17:20
We plan to rename `Analyzers` to `Writers` in v3: e.g. `hoomd.write.gsd(trigger=...)`. 

A more explicit name for the parameter could be `check_writer_triggers_on_initial_step`. Only writers that have triggers that return True on the initial step should be executed, so the parameter name gets verbose so as to not imply that all writers will execute regardless of their trigger.

**Comment by joaander** [comment] 2020-10-02 12:55
The PR is open for review: #783

**Closed** 2020-10-06 19:42 UTC
Labels: API 3.0, enhancement
