### ISSUE TITLE
Compile Error in HIP Header

### ISSUE THREAD

**Issue by ejmeitz** [glotzerlab/hoomd-blue#1452] opened 2022-12-14 02:38 UTC
### Description

I am trying to compile HOOMD with MPI and CUDA support. I am able to configure the build in CMake successfully; however, when I go to build the folder I get an error in one of the HIP headers.

### Script

```python
Configuration: cmake ../ -DENABLE_GPU=on -DENABLE_MPI=on -DCMAKE_C_COMPILER=/opt/rh/devtoolset-11/root/usr/bin/gcc -DCMAKE_CXX_COMPILER=/opt/rh/devtoolset-11/root/usr/bin/g++ -DHOOMD_GPU_PLATFORM=CUDA

This completes successfully (all dependencies are marked as present).
```

### Input files

N/A

### Output

```shell
Scanning dependencies of target _hoomd
[  2%] Building CXX object hoomd/CMakeFiles/_hoomd.dir/module.cc.o
In file included from /home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/hip_runtime_api.h:344,
                 from /home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/nvcc_detail/hip_runtime.h:28,
                 from /home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/hip_runtime.h:58,
                 from /home/emeitz/hoomd-blue/hoomd/HOOMDMath.h:13,
                 from /home/emeitz/hoomd-blue/hoomd/ExecutionConfiguration.h:8,
                 from /home/emeitz/hoomd-blue/hoomd/Autotuner.h:12,
                 from /home/emeitz/hoomd-blue/hoomd/Autotuned.h:15,
                 from /home/emeitz/hoomd-blue/hoomd/Action.h:14,
                 from /home/emeitz/hoomd-blue/hoomd/module.cc:4:
/home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/nvcc_detail/hip_runtime_api.h: In function ‘hipError_t hipBindTexture(size_t*, textureReference*, const void*, const hipChannelFormatDesc*, size_t)’:
/home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/nvcc_detail/hip_runtime_api.h:1381:35: error: ‘cudaBindTexture’ was not declared in this scope; did you mean ‘hipBindTexture’?
 1381 |     return hipCUDAErrorTohipError(cudaBindTexture(offset, tex, devPtr, desc, size));
      |                                   ^~~~~~~~~~~~~~~
      |                                   hipBindTexture
/home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/nvcc_detail/hip_runtime_api.h: In function ‘hipError_t hipGetTextureAlignmentOffset(size_t*, const textureReference*)’:
/home/emeitz/hoomd-blue/hoomd/extern/HIP/include/hip/nvcc_detail/hip_runtime_api.h:1417:35: error: ‘cudaGetTextureAlignmentOffset’ was not declared in this scope; did you mean ‘hipGetTextureAlignmentOffset’?
 1417 |     return hipCUDAErrorTohipError(cudaGetTextureAlignmentOffset(offset,texref));
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   hipGetTextureAlignmentOffset
gmake[2]: *** [hoomd/CMakeFiles/_hoomd.dir/build.make:83: hoomd/CMakeFiles/_hoomd.dir/module.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1111: hoomd/CMakeFiles/_hoomd.dir/all] Error 2
gmake: *** [Makefile:161: all] Error 2
```

### Expected output

I expected it to compile. I do not really know why an HIP header is throwing an error when I explicitly told it to use CUDA (which is also the default). If I go into the flags.make file there are a bunch of DENABLE_HIP and other HIP related flags. Maybe I don't know what HIP does but I did not expect those to be there.

### Platform

Linux

### Installation method

Compiled from source

### HOOMD-blue version

3.7.0

### Python version

3.6.8

**Comment by joaander** [comment] 2022-12-14 10:34
This is a duplicate of #1450. Yes, the message is slightly different - but the underlying error is the same. `cudaBindTexture` doesn't exist in CUDA 12. Downgrade to CUDA 11. I will add support for CUDA 12 in the next release.

HOOMD uses HIP to support both NVIDIA (via CUDA) and AMD (via rocm) GPUs. See https://github.com/glotzerlab/hoomd-blue/blob/trunk-patch/ARCHITECTURE.md for details.

**Closed as completed** 2022-12-14 17:35 UTC
Labels: bug, duplicate
